// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcawbNmaacIXThI9NUyI6kKM1tjvjU9yo',
    appId: '1:872108032114:web:a75c1eae1622484f8342eb',
    messagingSenderId: '872108032114',
    projectId: 'test-4cf8c',
    authDomain: 'test-4cf8c.firebaseapp.com',
    storageBucket: 'test-4cf8c.firebasestorage.app',
    measurementId: 'G-5X1VX0N38S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJDFskzE95L7uib-3hYzS1aBsqdAwU1dM',
    appId: '1:872108032114:android:1f552dc9d56fbcbd8342eb',
    messagingSenderId: '872108032114',
    projectId: 'test-4cf8c',
    storageBucket: 'test-4cf8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAos6oL5gBI_AduCeMKMXxiQukWLjsd0i0',
    appId: '1:872108032114:ios:a007c9c6284f21a38342eb',
    messagingSenderId: '872108032114',
    projectId: 'test-4cf8c',
    storageBucket: 'test-4cf8c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAos6oL5gBI_AduCeMKMXxiQukWLjsd0i0',
    appId: '1:872108032114:ios:a007c9c6284f21a38342eb',
    messagingSenderId: '872108032114',
    projectId: 'test-4cf8c',
    storageBucket: 'test-4cf8c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
